"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf import wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _LogLevel:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _LogLevelEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_LogLevel.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    NONE: _LogLevel.ValueType  # 0
    INFO: _LogLevel.ValueType  # 1
    DEBUG: _LogLevel.ValueType  # 2
    WARNING: _LogLevel.ValueType  # 3
    ERROR: _LogLevel.ValueType  # 4
    AUDIT: _LogLevel.ValueType  # 5

class LogLevel(_LogLevel, metaclass=_LogLevelEnumTypeWrapper):
    """Status"""

NONE: LogLevel.ValueType  # 0
INFO: LogLevel.ValueType  # 1
DEBUG: LogLevel.ValueType  # 2
WARNING: LogLevel.ValueType  # 3
ERROR: LogLevel.ValueType  # 4
AUDIT: LogLevel.ValueType  # 5
Global___LogLevel: _TypeAlias = LogLevel  # noqa: Y015

class _ModelStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ModelStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ModelStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    UNKNOWN: _ModelStatus.ValueType  # 0
    IN_PROGRESS: _ModelStatus.ValueType  # 1
    OK: _ModelStatus.ValueType  # 2
    FAILED: _ModelStatus.ValueType  # 3

class ModelStatus(_ModelStatus, metaclass=_ModelStatusEnumTypeWrapper):
    """ModelService"""

UNKNOWN: ModelStatus.ValueType  # 0
IN_PROGRESS: ModelStatus.ValueType  # 1
OK: ModelStatus.ValueType  # 2
FAILED: ModelStatus.ValueType  # 3
Global___ModelStatus: _TypeAlias = ModelStatus  # noqa: Y015

@_typing.final
class Response(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESPONSE_FIELD_NUMBER: _builtins.int
    PARAMETERS_FIELD_NUMBER: _builtins.int
    response: _builtins.str
    parameters: _builtins.str
    def __init__(
        self,
        *,
        response: _builtins.str = ...,
        parameters: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["parameters", b"parameters", "response", b"response"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Response: _TypeAlias = Response  # noqa: Y015

@_typing.final
class Status(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CLIENT_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    LOG_LEVEL_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    client_id: _builtins.str
    status: _builtins.str
    log_level: Global___LogLevel.ValueType
    type: _builtins.str
    @_builtins.property
    def timestamp(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        client_id: _builtins.str = ...,
        status: _builtins.str = ...,
        log_level: Global___LogLevel.ValueType = ...,
        timestamp: _timestamp_pb2.Timestamp | None = ...,
        type: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["timestamp", b"timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_id", b"client_id", "log_level", b"log_level", "status", b"status", "timestamp", b"timestamp", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Status: _TypeAlias = Status  # noqa: Y015

@_typing.final
class ModelUpdate(_message.Message):
    """Combiner from Client"""

    DESCRIPTOR: _descriptor.Descriptor

    CLIENT_ID_FIELD_NUMBER: _builtins.int
    MODEL_ID_FIELD_NUMBER: _builtins.int
    MODEL_UPDATE_ID_FIELD_NUMBER: _builtins.int
    CORRELATION_ID_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    META_FIELD_NUMBER: _builtins.int
    CONFIG_FIELD_NUMBER: _builtins.int
    ROUND_ID_FIELD_NUMBER: _builtins.int
    SESSION_ID_FIELD_NUMBER: _builtins.int
    client_id: _builtins.str
    model_id: _builtins.str
    model_update_id: _builtins.str
    correlation_id: _builtins.str
    meta: _builtins.str
    config: _builtins.str
    round_id: _builtins.str
    session_id: _builtins.str
    @_builtins.property
    def timestamp(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        client_id: _builtins.str = ...,
        model_id: _builtins.str = ...,
        model_update_id: _builtins.str = ...,
        correlation_id: _builtins.str = ...,
        timestamp: _timestamp_pb2.Timestamp | None = ...,
        meta: _builtins.str = ...,
        config: _builtins.str = ...,
        round_id: _builtins.str = ...,
        session_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["timestamp", b"timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_id", b"client_id", "config", b"config", "correlation_id", b"correlation_id", "meta", b"meta", "model_id", b"model_id", "model_update_id", b"model_update_id", "round_id", b"round_id", "session_id", b"session_id", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ModelUpdate: _TypeAlias = ModelUpdate  # noqa: Y015

@_typing.final
class ModelValidation(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CLIENT_ID_FIELD_NUMBER: _builtins.int
    MODEL_ID_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    CORRELATION_ID_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    SESSION_ID_FIELD_NUMBER: _builtins.int
    client_id: _builtins.str
    model_id: _builtins.str
    data: _builtins.str
    correlation_id: _builtins.str
    session_id: _builtins.str
    @_builtins.property
    def timestamp(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        client_id: _builtins.str = ...,
        model_id: _builtins.str = ...,
        data: _builtins.str = ...,
        correlation_id: _builtins.str = ...,
        timestamp: _timestamp_pb2.Timestamp | None = ...,
        session_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["timestamp", b"timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_id", b"client_id", "correlation_id", b"correlation_id", "data", b"data", "model_id", b"model_id", "session_id", b"session_id", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ModelValidation: _TypeAlias = ModelValidation  # noqa: Y015

@_typing.final
class ModelMetric(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CLIENT_ID_FIELD_NUMBER: _builtins.int
    METRICS_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    STEP_FIELD_NUMBER: _builtins.int
    MODEL_ID_FIELD_NUMBER: _builtins.int
    ROUND_ID_FIELD_NUMBER: _builtins.int
    SESSION_ID_FIELD_NUMBER: _builtins.int
    client_id: _builtins.str
    model_id: _builtins.str
    round_id: _builtins.str
    session_id: _builtins.str
    @_builtins.property
    def metrics(self) -> _containers.RepeatedCompositeFieldContainer[Global___MetricElem]: ...
    @_builtins.property
    def timestamp(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def step(self) -> _wrappers_pb2.UInt32Value: ...
    def __init__(
        self,
        *,
        client_id: _builtins.str = ...,
        metrics: _abc.Iterable[Global___MetricElem] | None = ...,
        timestamp: _timestamp_pb2.Timestamp | None = ...,
        step: _wrappers_pb2.UInt32Value | None = ...,
        model_id: _builtins.str = ...,
        round_id: _builtins.str = ...,
        session_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["step", b"step", "timestamp", b"timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_id", b"client_id", "metrics", b"metrics", "model_id", b"model_id", "round_id", b"round_id", "session_id", b"session_id", "step", b"step", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ModelMetric: _TypeAlias = ModelMetric  # noqa: Y015

@_typing.final
class MetricElem(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.float
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        value: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MetricElem: _TypeAlias = MetricElem  # noqa: Y015

@_typing.final
class AttributeMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CLIENT_ID_FIELD_NUMBER: _builtins.int
    ATTRIBUTES_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    client_id: _builtins.str
    @_builtins.property
    def attributes(self) -> _containers.RepeatedCompositeFieldContainer[Global___AttributeElem]: ...
    @_builtins.property
    def timestamp(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        client_id: _builtins.str = ...,
        attributes: _abc.Iterable[Global___AttributeElem] | None = ...,
        timestamp: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["timestamp", b"timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attributes", b"attributes", "client_id", b"client_id", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AttributeMessage: _TypeAlias = AttributeMessage  # noqa: Y015

@_typing.final
class AttributeElem(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.str
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        value: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AttributeElem: _TypeAlias = AttributeElem  # noqa: Y015

@_typing.final
class TelemetryMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CLIENT_ID_FIELD_NUMBER: _builtins.int
    TELEMETRIES_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    RECORD_ID_FIELD_NUMBER: _builtins.int
    client_id: _builtins.str
    record_id: _builtins.str
    @_builtins.property
    def telemetries(self) -> _containers.RepeatedCompositeFieldContainer[Global___TelemetryElem]: ...
    @_builtins.property
    def timestamp(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        client_id: _builtins.str = ...,
        telemetries: _abc.Iterable[Global___TelemetryElem] | None = ...,
        timestamp: _timestamp_pb2.Timestamp | None = ...,
        record_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["timestamp", b"timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_id", b"client_id", "record_id", b"record_id", "telemetries", b"telemetries", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TelemetryMessage: _TypeAlias = TelemetryMessage  # noqa: Y015

@_typing.final
class TelemetryElem(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.float
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        value: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TelemetryElem: _TypeAlias = TelemetryElem  # noqa: Y015

@_typing.final
class TelemetryRecord(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TELEMETRY_ID_FIELD_NUMBER: _builtins.int
    CLIENT_ID_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    telemetry_id: _builtins.str
    client_id: _builtins.str
    key: _builtins.str
    payload: _builtins.str
    @_builtins.property
    def timestamp(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        telemetry_id: _builtins.str = ...,
        client_id: _builtins.str = ...,
        timestamp: _timestamp_pb2.Timestamp | None = ...,
        key: _builtins.str = ...,
        payload: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["timestamp", b"timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_id", b"client_id", "key", b"key", "payload", b"payload", "telemetry_id", b"telemetry_id", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TelemetryRecord: _TypeAlias = TelemetryRecord  # noqa: Y015

@_typing.final
class AttributeRecord(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ATTRIBUTE_ID_FIELD_NUMBER: _builtins.int
    CLIENT_ID_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    attribute_id: _builtins.str
    client_id: _builtins.str
    key: _builtins.str
    payload: _builtins.str
    @_builtins.property
    def timestamp(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        attribute_id: _builtins.str = ...,
        client_id: _builtins.str = ...,
        timestamp: _timestamp_pb2.Timestamp | None = ...,
        key: _builtins.str = ...,
        payload: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["timestamp", b"timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attribute_id", b"attribute_id", "client_id", b"client_id", "key", b"key", "payload", b"payload", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AttributeRecord: _TypeAlias = AttributeRecord  # noqa: Y015

@_typing.final
class RecordAck(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RECORD_IDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def record_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        record_ids: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["record_ids", b"record_ids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RecordAck: _TypeAlias = RecordAck  # noqa: Y015

@_typing.final
class InferenceResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INFERENCE_RESULT_ID_FIELD_NUMBER: _builtins.int
    NODE_ID_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    INFERENCE_ID_FIELD_NUMBER: _builtins.int
    MODEL_ID_FIELD_NUMBER: _builtins.int
    inference_result_id: _builtins.str
    node_id: _builtins.str
    key: _builtins.str
    payload: _builtins.str
    inference_id: _builtins.str
    model_id: _builtins.str
    @_builtins.property
    def timestamp(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        inference_result_id: _builtins.str = ...,
        node_id: _builtins.str = ...,
        timestamp: _timestamp_pb2.Timestamp | None = ...,
        key: _builtins.str = ...,
        payload: _builtins.str = ...,
        inference_id: _builtins.str = ...,
        model_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["timestamp", b"timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["inference_id", b"inference_id", "inference_result_id", b"inference_result_id", "key", b"key", "model_id", b"model_id", "node_id", b"node_id", "payload", b"payload", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___InferenceResult: _TypeAlias = InferenceResult  # noqa: Y015

@_typing.final
class TaskRequest(_message.Message):
    """Task related"""

    DESCRIPTOR: _descriptor.Descriptor

    MODEL_ID_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    CORRELATION_ID_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    SESSION_ID_FIELD_NUMBER: _builtins.int
    ROUND_ID_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    CLIENT_ID_FIELD_NUMBER: _builtins.int
    model_id: _builtins.str
    data: _builtins.str
    correlation_id: _builtins.str
    timestamp: _builtins.str
    session_id: _builtins.str
    round_id: _builtins.str
    type: _builtins.str
    status: _builtins.str
    client_id: _builtins.str
    def __init__(
        self,
        *,
        model_id: _builtins.str = ...,
        data: _builtins.str = ...,
        correlation_id: _builtins.str = ...,
        timestamp: _builtins.str = ...,
        session_id: _builtins.str = ...,
        round_id: _builtins.str = ...,
        type: _builtins.str = ...,
        status: _builtins.str = ...,
        client_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_id", b"client_id", "correlation_id", b"correlation_id", "data", b"data", "model_id", b"model_id", "round_id", b"round_id", "session_id", b"session_id", "status", b"status", "timestamp", b"timestamp", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TaskRequest: _TypeAlias = TaskRequest  # noqa: Y015

@_typing.final
class ActivityReport(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NODE_ID_FIELD_NUMBER: _builtins.int
    CORRELATION_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    DONE_FIELD_NUMBER: _builtins.int
    RESPONSE_FIELD_NUMBER: _builtins.int
    node_id: _builtins.str
    """If sent from a client"""
    correlation_id: _builtins.str
    status: _builtins.str
    done: _builtins.bool
    response: _builtins.str
    """json"""
    def __init__(
        self,
        *,
        node_id: _builtins.str = ...,
        correlation_id: _builtins.str = ...,
        status: _builtins.str = ...,
        done: _builtins.bool = ...,
        response: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["correlation_id", b"correlation_id", "done", b"done", "node_id", b"node_id", "response", b"response", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ActivityReport: _TypeAlias = ActivityReport  # noqa: Y015

@_typing.final
class Heartbeat(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CLIENT_ID_FIELD_NUMBER: _builtins.int
    HEARTBEAT_INTERVAL_MS_FIELD_NUMBER: _builtins.int
    client_id: _builtins.str
    heartbeat_interval_ms: _builtins.int
    def __init__(
        self,
        *,
        client_id: _builtins.str = ...,
        heartbeat_interval_ms: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_heartbeat_interval_ms", b"_heartbeat_interval_ms", "heartbeat_interval_ms", b"heartbeat_interval_ms"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_heartbeat_interval_ms", b"_heartbeat_interval_ms", "client_id", b"client_id", "heartbeat_interval_ms", b"heartbeat_interval_ms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__heartbeat_interval_ms: _TypeAlias = _typing.Literal["heartbeat_interval_ms"]  # noqa: Y015
    _WhichOneofArgType__heartbeat_interval_ms: _TypeAlias = _typing.Literal["_heartbeat_interval_ms", b"_heartbeat_interval_ms"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__heartbeat_interval_ms) -> _WhichOneofReturnType__heartbeat_interval_ms | None: ...

Global___Heartbeat: _TypeAlias = Heartbeat  # noqa: Y015

@_typing.final
class ClientAvailableMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CLIENT_ID_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    client_id: _builtins.str
    data: _builtins.str
    timestamp: _builtins.str
    def __init__(
        self,
        *,
        client_id: _builtins.str = ...,
        data: _builtins.str = ...,
        timestamp: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_id", b"client_id", "data", b"data", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ClientAvailableMessage: _TypeAlias = ClientAvailableMessage  # noqa: Y015

@_typing.final
class ClientAnnounceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CLIENT_ID_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    PARAMETERS_FIELD_NUMBER: _builtins.int
    client_id: _builtins.str
    type: _builtins.str
    parameters: _builtins.str
    def __init__(
        self,
        *,
        client_id: _builtins.str = ...,
        type: _builtins.str = ...,
        parameters: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_id", b"client_id", "parameters", b"parameters", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ClientAnnounceRequest: _TypeAlias = ClientAnnounceRequest  # noqa: Y015

@_typing.final
class BacklogReport(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CLIENT_ID_FIELD_NUMBER: _builtins.int
    BACKLOG_TOTAL_FIELD_NUMBER: _builtins.int
    BACKLOG_DROPPED_TOTAL_FIELD_NUMBER: _builtins.int
    BACKLOG_OLDEST_AGE_MS_FIELD_NUMBER: _builtins.int
    client_id: _builtins.str
    backlog_total: _builtins.int
    backlog_dropped_total: _builtins.int
    backlog_oldest_age_ms: _builtins.float
    def __init__(
        self,
        *,
        client_id: _builtins.str = ...,
        backlog_total: _builtins.int = ...,
        backlog_dropped_total: _builtins.int = ...,
        backlog_oldest_age_ms: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_backlog_oldest_age_ms", b"_backlog_oldest_age_ms", "backlog_oldest_age_ms", b"backlog_oldest_age_ms"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_backlog_oldest_age_ms", b"_backlog_oldest_age_ms", "backlog_dropped_total", b"backlog_dropped_total", "backlog_oldest_age_ms", b"backlog_oldest_age_ms", "backlog_total", b"backlog_total", "client_id", b"client_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__backlog_oldest_age_ms: _TypeAlias = _typing.Literal["backlog_oldest_age_ms"]  # noqa: Y015
    _WhichOneofArgType__backlog_oldest_age_ms: _TypeAlias = _typing.Literal["_backlog_oldest_age_ms", b"_backlog_oldest_age_ms"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__backlog_oldest_age_ms) -> _WhichOneofReturnType__backlog_oldest_age_ms | None: ...

Global___BacklogReport: _TypeAlias = BacklogReport  # noqa: Y015

@_typing.final
class ClientReport(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CLIENT_ID_FIELD_NUMBER: _builtins.int
    REPORTS_FIELD_NUMBER: _builtins.int
    POLL_INTERVAL_MS_FIELD_NUMBER: _builtins.int
    SKIP_POLLING_TASKS_FIELD_NUMBER: _builtins.int
    client_id: _builtins.str
    poll_interval_ms: _builtins.int
    skip_polling_tasks: _builtins.bool
    @_builtins.property
    def reports(self) -> _containers.RepeatedCompositeFieldContainer[Global___ActivityReport]: ...
    def __init__(
        self,
        *,
        client_id: _builtins.str = ...,
        reports: _abc.Iterable[Global___ActivityReport] | None = ...,
        poll_interval_ms: _builtins.int | None = ...,
        skip_polling_tasks: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_poll_interval_ms", b"_poll_interval_ms", "poll_interval_ms", b"poll_interval_ms"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_poll_interval_ms", b"_poll_interval_ms", "client_id", b"client_id", "poll_interval_ms", b"poll_interval_ms", "reports", b"reports", "skip_polling_tasks", b"skip_polling_tasks"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__poll_interval_ms: _TypeAlias = _typing.Literal["poll_interval_ms"]  # noqa: Y015
    _WhichOneofArgType__poll_interval_ms: _TypeAlias = _typing.Literal["_poll_interval_ms", b"_poll_interval_ms"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__poll_interval_ms) -> _WhichOneofReturnType__poll_interval_ms | None: ...

Global___ClientReport: _TypeAlias = ClientReport  # noqa: Y015

@_typing.final
class CombinerDirective(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TASKS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def tasks(self) -> _containers.RepeatedCompositeFieldContainer[Global___TaskRequest]: ...
    def __init__(
        self,
        *,
        tasks: _abc.Iterable[Global___TaskRequest] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tasks", b"tasks"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CombinerDirective: _TypeAlias = CombinerDirective  # noqa: Y015

@_typing.final
class ModelRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MODEL_ID_FIELD_NUMBER: _builtins.int
    model_id: _builtins.str
    def __init__(
        self,
        *,
        model_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["model_id", b"model_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ModelRequest: _TypeAlias = ModelRequest  # noqa: Y015

@_typing.final
class FileChunk(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    def __init__(
        self,
        *,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FileChunk: _TypeAlias = FileChunk  # noqa: Y015

@_typing.final
class ModelResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STATUS_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    status: Global___ModelStatus.ValueType
    message: _builtins.str
    def __init__(
        self,
        *,
        status: Global___ModelStatus.ValueType = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ModelResponse: _TypeAlias = ModelResponse  # noqa: Y015
