[project]
name = "scaleout"
version = "1.1.0"
description = "A client library for the Scaleout Edge"
authors = [{ name = "Scaleout Systems AB" }]
requires-python = ">=3.11, <3.14"
readme = "README.rst"
license = "Apache-2.0"
dependencies = [
    "psutil",
    "scaleoututil==1.1.0",
    "click==8.5.0",
    "urllib3>=2.6.0",
    "filelock>=3.32.6",
]

[project.urls]
Homepage = "https://scaleoutsystems.com"
Documentation = "https://docs.scaleoutsystems.com/en/latest/"

[project.optional-dependencies]
test = [
    "pytest==9.1.1",
    "pytest-cov>=7.1.0",
    "responses>=0.26.3",
]

[project.scripts]
scaleout = "scaleout.cli.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
scaleoututil = { workspace = true }

[tool.pytest.ini_options]
testpaths = ["scaleout", "tests"]
addopts = "--doctest-modules --cov=scaleout-core --cov-report=term-missing --cov-report=xml --cov-report=html"
